### ISSUE TITLE
Why doesn't the privacy thing close?

### ISSUE THREAD

**Issue by ILOVETOMAKESTUFF** [The-Forum-Participators/the-forum-participators.github.io#15]
https://github.com/The-Forum-Participators/the-forum-participators.github.io/blob/e292e81aed84ca89d6dfed28f564c6b9ff97c2b7/index.html#L37
What did I do wrong? `onclick="document.getElementById("privacyWarning").style.display = "none";"`

**Comment by devluki** [comment]
Hi, it would be good idea to put javascript code in separate file or in <script></script> tags than inline in HTML :). In this case your bug is result of too many apostrophes. Try this code instead, with external double quotation marks and inner single quotation marks :

 <button class="privacyButton"
            onclick="document.getElementById('privacyWarning').style.display = 'none';">Okay</button> <button
            class="privacyButton">Leave Site</button>

**Comment by ILOVETOMAKESTUFF** [comment]
@devluki Okay, I'll retry... 😉

**Comment by ILOVETOMAKESTUFF** [comment]
It still doesn't work

**Comment by devluki** [comment]
Ok, show me your code

**Comment by devluki** [comment]
Check this example https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onclick_html

**Comment by devluki** [comment]
By the way, solution from my first post is working (if you put this code inline inside button tags, like in oryginal code)
